Repository teaxyz/white-paper, pull requests merged in 2022-09, with the labels that each got.

#75 add indonesia translation
  i18n/id/metadata.yml
  i18n/id/white-paper.md
Labels: Translation

#88 Push translations without release
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/make.yml
  .github/workflows/release.yml
Labels: bug, enhancement

#86 Fix: minor improvements to the visualization of the Indonesian pdf
  i18n/id/white-paper.md
Labels: enhancement

#87 Additional template steps
  .github/pull_request_template.md
Labels: enhancement
